sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.8.128
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: localhost
    access-key-secret: localhost
    bucket-name: sky-take-out
  redis:
    host: 192.168.8.128
    port: 6379
    password:
    database: 10
  wechat:
    appid: localhost
    secret: localhost
    mchid: localhost
    mchSerialNo: localhost
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: localhost
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php